# Generated by Django 5.1.6 on 2025-03-03 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Group')),
                ('nature', models.CharField(choices=[('none', 'None'), ('must', 'Must'), ('need', 'Need'), ('want', 'Want')], default=('none', 'None'), max_length=5, verbose_name='Nature')),
                ('spent', models.FloatField(default=0, verbose_name='Spent')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Name')),
                ('currency', models.CharField(choices=[('usd', 'US Dollar'), ('eur', 'EU Euro'), ('cny', 'CN Yuan'), ('rub', 'RU Rouble'), ('aed', 'AE Dirham'), ('azn', 'AZ Manat'), ('btc', 'Bitcoin'), ('byn', 'BY Rouble'), ('gel', 'GR Lari'), ('ils', 'IS Sheqel'), ('ind', 'IN Rupee'), ('kgs', 'KG Som'), ('kpw', 'NK Won'), ('kzt', 'KZ Tenge'), ('ngn', 'NG Laira'), ('rsd', 'RS Dinar'), ('sar', 'SA Riyal'), ('tjs', 'TJ Somoni'), ('tmt', 'TM Manat'), ('try', 'TR Lira'), ('uzs', 'UZ Com'), ('zar', 'SA Rand')], default=('rub', 'RU Rouble'), max_length=30, verbose_name='Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[('income', 'Income'), ('expence', 'Expence'), ('transfer', 'Transfer')], default='expence', max_length=15, verbose_name='Type')),
                ('amount', models.FloatField(blank=True, verbose_name='Amount')),
                ('date_time', models.DateTimeField(verbose_name='Date and time')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='logic.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='logic.category')),
            ],
        ),
    ]
