# Generated by Django 5.1.6 on 2025-03-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_alter_record_type_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='type_of',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], default='expense', max_length=15, verbose_name='Type'),
        ),
    ]
